/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEF = 4;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int TRUE = 8;
  /** RegularExpression Id. */
  int FALSE = 9;
  /** RegularExpression Id. */
  int EQUAL = 10;
  /** RegularExpression Id. */
  int DIFFERENT = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int GREATER = 13;
  /** RegularExpression Id. */
  int SMALLER = 14;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 15;
  /** RegularExpression Id. */
  int SMALLER_EQUAL = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int THEN = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int EXIT = 20;
  /** RegularExpression Id. */
  int WHILE = 21;
  /** RegularExpression Id. */
  int DO = 22;
  /** RegularExpression Id. */
  int Id = 23;
  /** RegularExpression Id. */
  int Num = 24;
  /** RegularExpression Id. */
  int PLUS = 25;
  /** RegularExpression Id. */
  int MINUS = 26;
  /** RegularExpression Id. */
  int TIMES = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int LPAR = 29;
  /** RegularExpression Id. */
  int RPAR = 30;
  /** RegularExpression Id. */
  int EQ = 31;
  /** RegularExpression Id. */
  int SEMICOL = 32;
  /** RegularExpression Id. */
  int ASSIGN = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int EL = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"def\"",
    "\"in\"",
    "\"end\"",
    "\"||\"",
    "\"true\"",
    "\"false\"",
    "\"==\"",
    "\"!=\"",
    "\"!\"",
    "\">\"",
    "\"< \"",
    "\" >=\"",
    "\"<=\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"exit\"",
    "\"while\"",
    "\"do\"",
    "<Id>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"|\"",
    "\";\"",
    "\":=\"",
    "\"&&\"",
    "\"\\n\"",
  };

}
